spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://db:3306/
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always

logging:
  level:
    root: info
    org:
      hibernate:
        type: trace
